--changeset  michalenok:1.0.0
CREATE TABLE sensor_statistics (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   date DATE NOT NULL,
                                   total_sensors INT NOT NULL
);
--rollback DROP TABLE sensor_statistics;

CREATE TABLE sensor_types_count (
                                    statistics_id BIGINT NOT NULL,
                                    sensor_type VARCHAR(255) NOT NULL,
                                    count INT NOT NULL,
                                    CONSTRAINT fk_sensor_statistics FOREIGN KEY (statistics_id) REFERENCES sensor_statistics(id)
);
