server:
  port: 8081
spring:
  application:
    name: statistics
  datasource:
    url: jdbc:postgresql://database-statistics:5432/postgres
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    date-format: dd.MM.yyyy
management:
  endpoints:
    web:
      exposure:
        include: quartz
  endpoint:
    quartz:
      access: unrestricted
url:
  login: 'http://monitor-sensors:8080/auth/login'
  sensors: 'http://monitor-sensors:8080/sensors'
job:
  sensorStatisticsJob:
    login: 'admin'
    password: 'admin'
    trigger:
      hour: '0'
      minute: '20'